export const ingressosDisponiveis = [
  {
    tipo: "Social 🤝",
    nome: "Conexão Popular",
    preco: "R$30,00",
    classe: "social",
    obs: "*Ingresso social para ações inclusivas",
  },
  {
    tipo: "Estudante 🎓",
    nome: "Mente Brilhante",
    preco: "R$40,00",
    classe: "estudante",
    obs: "*Desconto para estudantes com documento",
  },
  {
    tipo: "PCD ♿",
    nome: "Acesso Livre",
    preco: "R$0,00",
    classe: "pcd",
    obs: "*Acesso adaptado para pessoas com deficiência",
  },
  {
    tipo: "Pista ⚡",
    nome: "Pulse Zone",
    preco: "R$90,00",
    classe: "pista",
    obs: "*Área geral com energia e movimento",
  },
  {
    tipo: "Camarote 🪩",
    nome: "Vista Lounge",
    preco: "R$280,00",
    classe: "camarote",
    obs: "*Visão privilegiada e espaço elevado",
  },
  {
    tipo: "Camarote PLUS 🍾",
    nome: "Imperial Lounge",
    preco: "R$300,00",
    classe: "camarote-plus",
    obs: "*Inclui lounge exclusivo e serviços extras",
  },
  {
    tipo: "Premium 🌕",
    nome: "Eclipse Gold",
    preco: "R$340,00",
    classe: "premium",
    obs: "*Benefícios premium e localização especial",
  },
  {
    tipo: "VIP 👑",
    nome: "Aurora Prime",
    preco: "R$450,00",
    classe: "vip",
    obs: "*Acesso prioritário e área VIP exclusiva",
  },
];
